import React from "react";
import { ScrollView, StyleSheet } from "react-native";
import styled from "styled-components/native";

interface Props {
  description: string;
}

export default function DescriptionBook(props: Props) {
  const { description } = props;
  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Description>{description}</Description>
    </ScrollView>
  );
}

DescriptionBook.defaultProps = {
  description: `JDIOAJSD JSDIOJAOSJID AIOSJDAIOSJ DIOASJIODAJ IOAJSDOIAJS JIOASJDASIO
    askdpoaksdaopsk KODPAOKSDPAOKSD APSOKDAPSKDASOPKD ASDKOAPKSDPOAKSD
    SAKODKAPSDKA AKSDOPKAPSD AKSDPOAKSDPAKSPDK KAOPSDKAS
    APOSDKAPOSKDPOASKDPO ASKDOPAKSDP APSDKAPSOK PAOSKDPOAKSDOPASKDOPAKSDPOK
    SDKOPAKDSPAKSD PAOSKDPOAKSDOPASKDOPAKSDPOK SDKPAOSKD APSOKDAPSKDASOPKD
    DAPOSKDOAPSD DSKAOPSDKA SDAOPKSDAOPKSD AKSDOPAKSDPOAKSD KSDOPAKDPOAKSD
    SKDAOPKDSPOKAS JDIOAJSD JSDIOJAOSJID AIOSJDAIOSJ DIOASJIODAJ IOAJSDOIAJS
    JIOASJDASIO askdpoaksdaopsk KODPAOKSDPAOKSD APSOKDAPSKDASOPKD
    ASDKOAPKSDPOAKSD SAKODKAPSDKA AKSDOPKAPSD AKSDPOAKSDPAKSPDK KAOPSDKAS
    APOSDKAPOSKDPOASKDPO ASKDOPAKSDP APSDKAPSOK PAOSKDPOAKSDOPASKDOPAKSDPOK
    SDKOPAKDSPAKSD PAOSKDPOAKSDOPASKDOPAKSDPOK SDKPAOSKD APSOKDAPSKDASOPKD
    DAPOSKDOAPSD DSKAOPSDKA SDAOPKSDAOPKSD AKSDOPAKSDPOAKSD KSDOPAKDPOAKSD
    SKDAOPKDSPOKAS JDIOAJSD JSDIOJAOSJID AIOSJDAIOSJ DIOASJIODAJ IOAJSDOIAJS
    JIOASJDASIO askdpoaksdaopsk KODPAOKSDPAOKSD APSOKDAPSKDASOPKD
    ASDKOAPKSDPOAKSD SAKODKAPSDKA AKSDOPKAPSD AKSDPOAKSDPAKSPDK KAOPSDKAS
    APOSDKAPOSKDPOASKDPO ASKDOPAKSDP APSDKAPSOK PAOSKDPOAKSDOPASKDOPAKSDPOK
    SDKOPAKDSPAKSD PAOSKDPOAKSDOPASKDOPAKSDPOK SDKPAOSKD APSOKDAPSKDASOPKD
    DAPOSKDOAPSD DSKAOPSDKA SDAOPKSDAOPKSD AKSDOPAKSDPOAKSD KSDOPAKDPOAKSD
    SKDAOPKDSPOKAS`
};

const Description = styled.Text`
  line-height: 25;
`;

const styles = StyleSheet.create({
  container: {
    flex: 0,
    backgroundColor: "white",
    padding: 10
  }
});
